version: "1.0"
services:
  pyserver:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    environment:
      MONGODB_DATABASE: db
      MONGODB_USERNAME: user
      MONGODB_PASSWORD: 123
      MONGODB_HOSTNAME: mongodb
    volumes:
      - backenddata:/crawler/jobdir
      - ./backend/parser/model:/parser/model
    ports:
      - "8000:8000"
    networks:
      - app

  mongodb:
    image: mongo:4.0.8
    container_name: mongodb
    restart: unless-stopped
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 1234
      MONGO_INITDB_DATABASE: db
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - mongodbdata:/data/db
    ports:
      - "27017:27017"
    networks:
      - app

  webserver:
    build:
      context: frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      APP_ENV: "prod"
      APP_NAME: "webserver"
      APP_DEBUG: "true"
      SERVICE_NAME: "webserver"
    ports:
      - "3000:3000"
    networks:
      - app

networks:
  app:
    driver: bridge

volumes:
  mongodbdata:
    driver: local
  backenddata:
    driver: local
